export const weatherCodeVariables = {
  0: { condition: "Clear Sky", basePath: "images/clear_sky_" },
  1: { condition: "Mostly Clear", basePath: "images/clear_sky_" },
  2: { condition: "Partly Cloudy", basePath: "images/partly_cloudy_" },
  3: { condition: "Overcast", basePath: "images/overcast_" },
  45: { condition: "Foggy", basePath: "images/foggy_" },
  48: { condition: "Rime Fog", basePath: "images/foggy_" },
  51: { condition: "Light Drizzle", basePath: "images/rain_" },
  53: { condition: "Drizzle", basePath: "images/rain_" },
  55: { condition: "Heavy Drizzle", basePath: "images/rain_" },
  56: { condition: "Freezing Drizzle", basePath: "images/freezing_rain_" },
  57: { condition: "Freezing Drizzle", basePath: "images/freezing_rain_" },
  61: { condition: "Light Rain", basePath: "images/rain_" },
  63: { condition: "Rain", basePath: "images/rain_" },
  65: { condition: "Heavy Rain", basePath: "images/rain_" },
  66: { condition: "Freezing Rain", basePath: "images/freezing_rain_" },
  67: { condition: "Freezing Rain", basePath: "images/freezing_rain_" },
  71: { condition: "Light Snowfall", basePath: "images/snawfall_" },
  73: { condition: "Snowfall", basePath: "images/snawfall_" },
  75: { condition: "Heavy Snowfall", basePath: "images/snawfall_" },
  77: { condition: "Snow Grains", basePath: "images/snawfall_" },
  80: { condition: "Rain Showers", basePath: "images/rain_" },
  81: { condition: "Rain Showers", basePath: "images/rain_" },
  82: { condition: "Rain Showers", basePath: "images/rain_" },
  85: { condition: "Snow Showers", basePath: "images/snawfall_" },
  86: { condition: "Snow Showers", basePath: "images/snawfall_" },
  95: { condition: "Stormy", basePath: "images/stormy_" },
  96: { condition: "Stormy", basePath: "images/stormy_" },
  99: { condition: "Stormy", basePath: "images/stormy_" },
};
